### PR TITLE
Constraints on data fields

### PR DESCRIPTION
**Pull request by Raquel-Odhiambo**

### CODE REVIEW

**Comment by Symonss** [comment]
there is a conflicting file

**Comment by Symonss** [comment]
have you tested it?

**Comment by Raquel-Odhiambo** [comment]
Okay

**Comment by Raquel-Odhiambo** [comment]
Which one?

**Comment by Symonss** [comment]
I already solved and marged!

**Comment by Raquel-Odhiambo** [comment]
Okay. Transcendent work Coder!

**Pull request merged**
